### ISSUE TITLE
Latest jar doesn't seem to load right. Error on startup 

### ISSUE THREAD

**Issue by Geekmakes** [divios/DailyShop#67]
![2021-12-29_21 18 48](https://user-images.githubusercontent.com/16181272/147719005-1a22928d-afeb-4687-9a29-73f278513f1c.png)
This is all I'm getting in game

And in console:
https://pastebin.com/y7ZuF6bu

**Comment by divios** [comment]
The commands should be fixed on the new patch, sorry about that. For the other error I have to check it

**Comment by divios** [comment]
I just checked and the terminal error is caused beacuase vault cannot find a register, that means, an economy manager

**Comment by Geekmakes** [comment]
updated to the newest patch but I'm still getting the "here here" in chat.

Have the same error in console as well. Is it not compatible with CMI as a eco manager? both are vault based so I would think they'd be but maybe thats part of the problem. I haven't had this plugin working correctly yet since I got it so not sure whats required. 
Thanks!

**Comment by divios** [comment]
The help here shouldnt appear anymore in the newest update. It should work with CMI but I think you have to use and alternative version of it if i remember correctly.

Pd: this is required; Economy: For CMI economy to properly work you will need one of two solutions:
1. Is to use recompiled Vault version from HERE which has direct support for CMI economy and will have the best compatibility with other plugins.
2. Use economy injector from HERE which will add CMI economy support to any Vault build.
Both methods are valid but second one can have small issues with plugins which would tend to load straight after Vault loads and before injector himself.
P.S. Don't forget to enable Economy in a config file.

**Comment by Geekmakes** [comment]
Alright, that got rid of the error in console. However running commands doesn't bring anything up 

Is there anything you want me to uploaded that'd make this easier?

**Comment by Geekmakes** [comment]
Works now on latest. Thanks!
