### ISSUE TITLE
1.12.2 İtem İnsertion Errors

### ISSUE THREAD

**Issue by TeQTabanca** [divios/DailyShop#72]
![Create item from zero](https://user-images.githubusercontent.com/89253304/148367330-31ff3b52-9365-4eee-8501-c81965fa29ce.png)

### Error creating item from scratch:
**[10:14:31] [Server thread/ERROR]: Could not pass event InventoryClickEvent to DailyShop v3.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.divios.dailyShop.economies.vault
	at io.github.divios.lib.dLib.dItem.setItem(dItem.java:95) ~[?:?]
	at io.github.divios.lib.dLib.dItem.<init>(dItem.java:51) ~[?:?]
	at io.github.divios.lib.dLib.dItem.<init>(dItem.java:47) ~[?:?]
	at io.github.divios.dailyShop.guis.settings.shopGui.lambda$createGuis$7(shopGui.java:148) ~[?:?]
	at io.github.divios.dailyShop.guis.settings.addDailyGuiIH.lambda$body$0(addDailyGuiIH.java:53) ~[?:?]
	at io.github.divios.dependencies.Core_lib.inventory.ItemButton.onClick(ItemButton.java:65) ~[?:?]
	at io.github.divios.dependencies.Core_lib.inventory.InventoryGUI.onClick(InventoryGUI.java:479) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	... 15 more**

![Create item from existing](https://user-images.githubusercontent.com/89253304/148368326-0846ed3f-c573-4842-923d-13cbd01f1292.png)

### Existing item creation error:

**[10:24:32] [Server thread/WARN]: [DailyShop] Task #44 for DailyShop v3.6.0 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class io.github.divios.dailyShop.economies.vault
	at io.github.divios.lib.dLib.dItem.setItem(dItem.java:95) ~[?:?]
	at io.github.divios.lib.dLib.dItem.<init>(dItem.java:51) ~[?:?]
	at io.github.divios.lib.dLib.dItem.<init>(dItem.java:47) ~[?:?]
	at io.github.divios.dailyShop.guis.settings.shopGui.lambda$createGuis$7(shopGui.java:148) ~[?:?]
	at io.github.divios.dependencies.Core_lib.misc.ItemPrompt$ItemPromptBuilder.lambda$build$2(ItemPrompt.java:124) ~[?:?]
	at io.github.divios.dependencies.Core_lib.misc.ItemPrompt.lambda$OnPlayerClick$2(ItemPrompt.java:73) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]**

**Comment by divios** [comment]
Yep, this is related to [20](https://github.com/divios/DailyShop/issues/20), which is a really weird error that, sadly, it happens quite often for some reason I still cannot figure it out. From now on, I will try to upload the jar from my mac that seems to not give this error. Please add me on discord Divios#4093 and I will send a development build fixing this

**Comment by TeQTabanca** [comment]
I don't use Discord. It would be better if you upload the plugin here.

**Comment by divios** [comment]
https://mega.nz/file/cnYRHaBI#I_YPrJn55NFT7ju2bSVWEiSVVUVrNEmPV8sofnvMfc4

Let me know if it works, it should fix this issue and the other issue you also reported

**Comment by TeQTabanca** [comment]
### [19:38:59 INFO]: [Vault] Enabled Version 1.7.3-b131
**[19:39:08 INFO]: [DailyShop] Enabling DailyShop v3.6.5
[19:39:08 ERROR]: [DailyShop] Disabled due to: No economy provider found
[19:39:08 INFO]: [DailyShop] Disabling DailyShop v3.6.5**

**Comment by divios** [comment]
That makes sense, do you have an economy provider, like essentialsX?

**Comment by TeQTabanca** [comment]
**I set up this server to try out the plugins. I use essentialX on my real server but not on this server. I can add it if you want.**

**Comment by divios** [comment]
The only dependencies of the plugin are Vault and an economy manger, so i you are not using other then yes, add essentialsX since it is needed

**Comment by TeQTabanca** [comment]
**[19:53:33 INFO]: [DailyShop] Importing data from shops directory...
[19:53:33 INFO]: [NBTAPI] Found Spigot: v1_12_R1! Trying to find NMS support
[19:53:33 INFO]: [NBTAPI] NMS support 'MC1_12_R1' loaded!
[19:53:33 INFO]: [NBTAPI] Found Gson: class com.google.gson.Gson
[19:53:33 WARN]: [NBTAPI] The NBT-API at 'package io.github.divios.dependencies.nbt.nbtapi' seems to be a future Version, not yet released on Spigot/CurseForge!
[19:53:33 WARN]: [NBTAPI] Current Version: '2.9.0-SNAPSHOT' Newest Version: 2.8.0'
[19:53:34 WARN]: [DailyShop] There was a problem parsing the item with id PHANTOM_MEMBRANE
[19:53:34 WARN]: [DailyShop] null
[19:53:34 WARN]: [DailyShop] There was a problem parsing the item with id LEATHER_HORSE_ARMOR
[19:53:34 WARN]: [DailyShop] null
[19:53:34 WARN]: [DailyShop] There was a problem parsing the item with id TRIDENT
[19:53:34 WARN]: [DailyShop] null
[19:53:34 WARN]: [DailyShop] There was a problem parsing the item with id TURTLE_HELMET
[19:53:34 WARN]: [DailyShop] null
[19:53:35 INFO]: DailyShop > Renovated items of shop farm
[19:53:35 INFO]: [DailyShop] Registered shop of name farm with 64 items
[19:53:35 INFO]: DailyShop > Renovated items of shop wood
[19:53:35 INFO]: DailyShop > Renovated items of shop wood
[19:53:35 INFO]: DailyShop > Renovated items of shop wood
[19:53:35 INFO]: [DailyShop] Registered shop of name wood with 30 items
[19:53:35 INFO]: DailyShop > Renovated items of shop menu
[19:53:35 INFO]: DailyShop > Renovated items of shop menu
[19:53:35 INFO]: DailyShop > Renovated items of shop menu
[19:53:35 INFO]: [DailyShop] Registered shop of name menu with 0 items
[19:53:35 INFO]: [DailyShop] Data imported successfully in 1809 ms**

![dailyshop_time_blocks](https://user-images.githubusercontent.com/89253304/148444098-d14c97b6-2a77-4f0f-9d1b-34ddf811588a.png)
### [19:53:20 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1

**Is it normal for the placeholder not to load?**

**Comment by divios** [comment]
It should be displayed correctly, does the plugin register placeholderApi expansion correctly?

**Comment by divios** [comment]
And also does /papi parse me %dailyshop_time_blocks% display the time correctly?

**Comment by TeQTabanca** [comment]
**I ran the command you wrote. It doesn't show correctly.**

![papi parse me %dailyshop_time_blocks%](https://user-images.githubusercontent.com/89253304/148446940-3fc5fbfd-a698-402a-92a5-f74c41667f7d.png)

**Comment by divios** [comment]
Does on load display that the expansion has been loaded correctly? Like this:
![placeholderExample](https://user-images.githubusercontent.com/57331846/148447562-1cde1e55-9d0e-48e2-bbd6-6ac6b4420d1d.png)

**Comment by TeQTabanca** [comment]
**[19:53:30 INFO]: [DailyShop] Enabling DailyShop v3.6.5
[19:53:30 INFO]: [DailyShop] Hooked to Vault
[19:53:30 INFO]: [DailyShop] Reading lang.yml...
[19:53:30 INFO]: [DailyShop] Imported lang.yml in 82 ms
[19:53:30 INFO]: [DailyShop] Reading settings.yml...
[19:53:30 INFO]: [DailyShop] Imported settings.yml in 2 ms
[19:53:30 INFO]: [DailyShop] Reading priceModifiers.yml...
[19:53:30 INFO]: [DailyShop] Loaded 0 modifiers
[19:53:30 INFO]: [DailyShop] Imported priceModifier.yml in 1 ms
[19:53:30 INFO]: [DailyShop] Importing database data...
[19:53:30 INFO]: [DailyShop] Imported database data in 13 ms**

**Comment by TeQTabanca** [comment]
**I will check your message tomorrow because I have to sleep**

**Comment by divios** [comment]
Okay, [this one](https://we.tl/t-SXkJIMpY1E) should fix it along with the NullPointerException when trying to buy/sell an item on versions below <= 1.12. It works for me and I think the problem was that, before registering the papi extension, I check if the plugin "PlaceholderApi" is activated. It seems that in lower versions is case sensitive and needs to be "PlaceholderaAPI"

**Comment by TeQTabanca** [comment]
**I turned my server back on today.**

### Still not connected to placeholder.

- [06:14:12 INFO]: [DailyShop] Enabling DailyShop v3.6.5
- [06:14:12 INFO]: [DailyShop] Hooked to Vault
- [06:14:12 INFO]: [DailyShop] Reading lang.yml...
- [06:14:12 INFO]: [DailyShop] Imported lang.yml in 27 ms
- [06:14:12 INFO]: [DailyShop] Reading settings.yml...
- [06:14:12 INFO]: [DailyShop] Imported settings.yml in 6 ms
- [06:14:12 INFO]: [DailyShop] Reading priceModifiers.yml...
- [06:14:12 INFO]: [DailyShop] Loaded 0 modifiers
- [06:14:12 INFO]: [DailyShop] Imported priceModifier.yml in 1 ms
- [06:14:12 INFO]: [DailyShop] Importing database data...

### Could not open blocks.yml

- [06:14:16 INFO]: [DailyShop] Importing data from shops directory...
- [06:14:16 WARN]: [DailyShop] There was a problem with the shop blocks.yml
- [06:14:16 WARN]: java.lang.IllegalArgumentException: Invalid material
- [06:14:16 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dButtonAdapter.deserialize(dButtonAdapter.java:89)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dButtonAdapter.deserialize(dButtonAdapter.java:26)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:952)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dInventoryAdapter.deserialize(dInventoryAdapter.java:41)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dInventoryAdapter.deserialize(dInventoryAdapter.java:16)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:952)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:925)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dShopAdapter.deserialize(dShopAdapter.java:65)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.adapters.dShopAdapter.deserialize(dShopAdapter.java:20)
- [06:14:16 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:952)
- [06:14:16 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:925)
- [06:14:16 WARN]:        at io.github.divios.lib.serialize.serializerApi.getShopFromFile(serializerApi.java:43)
- [06:14:16 WARN]:        at io.github.divios.dailyShop.files.shopsResource.readYamlShops(shopsResource.java:114)
- [06:14:16 WARN]:        at io.github.divios.dailyShop.files.shopsResource.importYamlShops(shopsResource.java:51)
- [06:14:16 WARN]:        at io.github.divios.dailyShop.files.shopsResource.<init>(shopsResource.java:44)
- [06:14:16 WARN]:        at io.github.divios.dailyShop.files.resourceManager.lambda$new$0(resourceManager.java:27)
- [06:14:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
- [06:14:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
- [06:14:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
- [06:14:16 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
- [06:14:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
- [06:14:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
- [06:14:16 WARN]:        at java.lang.Thread.run(Thread.java:748)
- [06:14:16 WARN]: [DailyShop] Invalid material
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id PHANTOM_MEMBRANE
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id LEATHER_HORSE_ARMOR
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id TRIDENT
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id TURTLE_HELMET
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id SCUTE
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id DRIED_KELP_BLOCK
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id KELP
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id SEAGRASS
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id CARVED_PUMPKIN
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id SEA_PICKLE
- [06:14:16 WARN]: [DailyShop] null
- [06:14:16 WARN]: [DailyShop] There was a problem parsing the item with id DRIED_KELP
- [06:14:16 WARN]: [DailyShop] null
- [06:14:17 INFO]: [DailyShop] Registered shop of name drops with 20 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name potion with 42 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name ore with 24 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name equipment with 59 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name farm with 64 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name wood with 30 items
- [06:14:17 INFO]: [DailyShop] Registered shop of name menu with 0 items
- [06:14:17 INFO]: [DailyShop] Data imported successfully in 1044 ms

### I don't get error creating item from scratch.

### I'm getting an error creating a package item.

![Create a Bundle İtem](https://user-images.githubusercontent.com/89253304/148508702-894adb3d-acd9-4118-bdd0-d605352215b3.png)

- [06:19:22 ERROR]: Could not pass event InventoryClickEvent to DailyShop v3.6.5
- org.bukkit.event.EventException: null
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
- at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
- at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
- Caused by: java.lang.NullPointerException
- at io.github.divios.dailyShop.guis.customizerguis.changeBundleItem.open(changeBundleItem.java:51) ~[?:?]
- at io.github.divios.dailyShop.guis.customizerguis.changeBundleItem.<init>(changeBundleItem.java:42) ~[?:?]
- at io.github.divios.dailyShop.guis.customizerguis.changeBundleItem$changeBundleItemBuilder.prompt(changeBundleItem.java:132) ~[?:?]
- at io.github.divios.dailyShop.guis.settings.addDailyGuiIH.lambda$body$4(addDailyGuiIH.java:94) ~[?:?]
- at io.github.divios.dependencies.Core_lib.inventory.ItemButton.onClick(ItemButton.java:65) ~[?:?]
- at io.github.divios.dependencies.Core_lib.inventory.InventoryGUI.onClick(InventoryGUI.java:479) ~[?:?]
- at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
- at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
- at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- ... 15 more

### I don't get error creating current item form.

### 1 in stock and I added 2 items, 1 unlimited, but when I open the shop, the purchase and sale information does not appear.

### Stocked Item
![Stocked İtem](https://user-images.githubusercontent.com/89253304/148504686-7ae17de4-25fd-4ac2-990d-ece525116927.png)

### Unlimited Item

![Unlimited İtem](https://user-images.githubusercontent.com/89253304/148504702-fa96e028-7f55-4a40-962b-69afdeec9e3d.png)

### If i run out of stock of the stocked item and buy it again.

- [07:07:55 ERROR]: Could not pass event InventoryClickEvent to DailyShop v3.6.5
- org.bukkit.event.EventException: null
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
- at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
- at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
- Caused by: java.lang.NullPointerException

### İf i buy unlimited stock items as i can afford, i get an error message.

![Balance](https://user-images.githubusercontent.com/89253304/148506509-37decf5b-a556-4395-be6d-0244732fe994.png)

![Maximum Buy](https://user-images.githubusercontent.com/89253304/148507117-daa1c65d-4867-48a0-ab81-571a03c88ea0.png)

### If you look carefully, it gives the error message, but it also gives the item and nothing is done with that item.

![Error Message](https://user-images.githubusercontent.com/89253304/148507191-1fbc0695-c0a8-457e-bda9-07afa9a5cc6c.png)

### If I click on empty places in the shop I get an error.

![Empty Space](https://user-images.githubusercontent.com/89253304/148508312-04a0f407-420a-4aa0-b90b-12610383ee00.png)

- [07:32:49 ERROR]: Could not pass event InventoryClickEvent to DailyShop v3.6.5
- org.bukkit.event.EventException: null
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
- at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
- at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
- Caused by: java.lang.NullPointerException
- at io.github.divios.dailyShop.guis.customizerguis.customizeGui.upperInventoryAction(customizeGui.java:346) ~[?:?]
- at io.github.divios.dailyShop.guis.customizerguis.customizeGui.onInventoryClick(customizeGui.java:169) ~[?:?]
- at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
- at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
- at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
- at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
- at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
- ... 15 more

### İf i customize shop menu.

![Customize Shop Menü](https://user-images.githubusercontent.com/89253304/148510481-11b6c78c-6dae-46b2-b3a2-82b5c1c6159c.png)

### I want to set blocks.

![Customize Shop Menü Blocks](https://user-images.githubusercontent.com/89253304/148510522-818fc67c-eaa8-494e-adc1-6c0fe0045732.png)

![Customize Shop Menü Blocks 2](https://user-images.githubusercontent.com/89253304/148510553-419c6204-3387-4b42-98c2-5fde3581148c.png)

### I'm done with the menu. I press Apply Changes.

![Customize Shop Menü Apply Changes](https://user-images.githubusercontent.com/89253304/148510585-540c546e-cc71-4f03-8aac-9c6e437b5055.png)

### After pressing, the items in the menu remain with me.

![Customize Shop Menü Apply Changes 2](https://user-images.githubusercontent.com/89253304/148510638-f3f9b812-e2e6-4218-9e94-8498ef5b291c.png)

### NOTE
**I hope you understand. I use translation because my English is bad.**

**Comment by divios** [comment]
[This Build](https://we.tl/t-75Ts6VjmLF) should fix everything you listed here. The main problem is that I didn't take into account some things that work on > 1.12 but throw Exceptions on versions below.

I'm still not sure why placeholderApi is not working, I'm exactly following the indications in the wiki but it seems that works for me but for others no D:

**Comment by TeQTabanca** [comment]
**What if you add your placeholders to the ecloud of the placeholderApi?**

### Example:

**/papi ecloud download DailiyShop**

**Comment by divios** [comment]
I guess I could but it still doesn't resolve the main problem why it is not registering the expansion. Could you check if placeholderApi is being loaded before or after dailyshop?

**Comment by TeQTabanca** [comment]
- [13:37:45 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.1
- [13:37:45 INFO]: [PlaceholderAPI] Fetching available expansion information...
- [13:37:46 INFO]: [DailyShop] Enabling DailyShop v3.6.5
- [13:37:47 INFO]: [DailyShop] Hooked to Vault
- [13:37:47 INFO]: [DailyShop] Reading lang.yml...
- [13:37:47 INFO]: [DailyShop] Imported lang.yml in 78 ms
- [13:37:47 INFO]: [DailyShop] Reading settings.yml...
- [13:37:47 INFO]: [DailyShop] Imported settings.yml in 2 ms
- [13:37:47 INFO]: [DailyShop] Reading priceModifiers.yml...
- [13:37:47 INFO]: [DailyShop] Loaded 0 modifiers
- [13:37:47 INFO]: [DailyShop] Imported priceModifier.yml in 2 ms
- [13:37:47 INFO]: [DailyShop] Importing database data...

**Comment by divios** [comment]
Try this [one](https://we.tl/t-gFNWBdxGOt), I tried a workaroud that may work

**Comment by TeQTabanca** [comment]
- [13:46:07 INFO]: [DailyShop] Enabling DailyShop v3.6.5
- [13:46:07 INFO]: [DailyShop] Hooked to Vault
- [13:46:07 INFO]: [DailyShop] Reading lang.yml...
- [13:46:07 INFO]: [DailyShop] Imported lang.yml in 89 ms
- [13:46:07 INFO]: [DailyShop] Reading settings.yml...
- [13:46:07 INFO]: [DailyShop] Imported settings.yml in 16 ms
- [13:46:07 INFO]: [DailyShop] Reading priceModifiers.yml...
- [13:46:07 INFO]: [DailyShop] Loaded 0 modifiers
- [13:46:07 INFO]: [DailyShop] Imported priceModifier.yml in 2 ms
- [13:46:07 INFO]: [DailyShop] Importing database data...
- [13:46:07 INFO]: [DailyShop] Imported database data in 3 ms

**Comment by divios** [comment]
It should hook to placeholderApi a few seconds after load, check if the placeholder is working now

**Comment by TeQTabanca** [comment]
### Out in the last episode

- [13:46:13 INFO]: [DailyShop] Hooked to PlaceholderAPI
- [13:46:13 INFO]: [PlaceholderAPI] Successfully registered expansion: DailyShop [3.6.5]



> [This Build](https://we.tl/t-oesunpm3Zp) should fix everything you listed here. The main problem is that I didn't take into account some things that work on > 1.12 but throw Exceptions on versions below.
> 
> I'm still not sure why placeholderApi is not working, I'm exactly following the indications in the wiki but it seems that works for me but is not working for some of you for some unknown reason D:

### I'm sorry I couldn't see the link here. I tried that too and it worked.

- [13:50:44 INFO]: [DailyShop] Enabling DailyShop v3.6.5
- [13:50:44 INFO]: [DailyShop] Hooked to Vault
- [13:50:44 INFO]: [DailyShop] Hooked to PlaceholderAPI
- [13:50:44 INFO]: [PlaceholderAPI] Successfully registered expansion: DailyShop [3.6.5]
- [13:50:44 INFO]: [DailyShop] Reading lang.yml...
- [13:50:44 INFO]: [DailyShop] Imported lang.yml in 66 ms
- [13:50:44 INFO]: [DailyShop] Reading settings.yml...
- [13:50:44 INFO]: [DailyShop] Imported settings.yml in 3 ms
- [13:50:44 INFO]: [DailyShop] Reading priceModifiers.yml...
- [13:50:44 INFO]: [DailyShop] Loaded 0 modifiers
- [13:50:44 INFO]: [DailyShop] Imported priceModifier.yml in 2 ms
- [13:50:45 INFO]: [DailyShop] Importing database data...
- [13:50:45 INFO]: [DailyShop] Imported database data in 2 ms

**Comment by divios** [comment]
Finally, great. Thanks for reporting the bugs and being so patience. If you encounter more bugs, please do report them in here and I will fix them as soon as possible

**Comment by TeQTabanca** [comment]
### The plugin gives these errors when first opened. It does not give this error on the second boot.

- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id SCUTE
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id DRIED_KELP_BLOCK
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id KELP
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id SEAGRASS
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id CARVED_PUMPKIN
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id SEA_PICKLE
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?
- [13:50:49 WARN]: [DailyShop] There was a problem parsing the item with id DRIED_KELP
- [13:50:49 WARN]: [DailyShop] Material not supported in this version?

![Balance](https://user-images.githubusercontent.com/89253304/148506509-37decf5b-a556-4395-be6d-0244732fe994.png)

![Maximum Buy](https://user-images.githubusercontent.com/89253304/148557037-3f140739-c11f-4d1b-af78-65e7b3979efd.png)

### If you look carefully, it gives the error message, but it also gives the item and nothing is done with that item.

![Error Message](https://user-images.githubusercontent.com/89253304/148557099-24b05690-0daf-4c09-90c7-c5f4f3cccc36.png)

### Economy placeholders not working

![Economy placeholders not working](https://user-images.githubusercontent.com/89253304/148558232-9cc90461-a6ea-418b-be1a-83d85fda7936.png)

### Normal Name Not Appearing

![Normal Name Not Appearing](https://user-images.githubusercontent.com/89253304/148558424-709db1b7-7884-43fc-b15e-8dd72ac9d200.png)

**Comment by divios** [comment]
The error messages is fine, the default items generated are from 1.17, so some of them are no compatible on 1.12, thats what the message is saying. 

I will post a new update now that fix the economy placeholders.

Could you send me a video with the **"it gives the error message, but it also gives the item and nothing is done with that item."**, I'm not sure if I understand the error.

I also do not undestand what do you mean by normal name not appearing

**Comment by TeQTabanca** [comment]
**Do You Understand the Mistakes in the Video?**

**Comment by divios** [comment]
I will check it tomorrow since I'm not at home

**Comment by TeQTabanca** [comment]
### [Watch this video too.](https://s6.dosya.tc/server6/dvufnq/Error_Item.zip.html)

**Comment by divios** [comment]
Hi! Sorry mate, I've been ill this past days and I couldn't do anything, I will start to fix this bugs right now

**Comment by divios** [comment]
[This one](https://we.tl/t-ciNvszB3Pg) should solve the problem with the "no space" error. I cannot reproduce the other errors but I'm still looking into it

**Comment by TeQTabanca** [comment]
> [This one](https://we.tl/t-ciNvszB3Pg) should solve the problem with the "no space" error. `I cannot reproduce the other errors but I'm still looking into it`

**Have other issues been resolved? I wondered.**

**Comment by divios** [comment]
Yes, pretty much everything have been fixed. The last update should be solid and the bugs I’ve been reported are minor bugs, nothing game breaking. I will fix those as soon as I finish my exams

**Comment by TeQTabanca** [comment]
### Will the free version be updated?

### Why are you asking about the free version? 
**Cause I was using the free version on the first errors.**

### I'm sorry I didn't mention the free version in the first post. 😥

**Comment by divios** [comment]
Yeah... you should have said that earlier... well at least you contributed to fix errors so I'm glad, you can keep the versions I provided for you. 

Also yes, I will try to update the free version to fix this errors

**Comment by TeQTabanca** [comment]
Hi I downloaded the dailyshop 3.7B free Version but if I add an item and it asks for permission to buy or sell. Even though I'm OP Minecraft Version 1.12.2

**Comment by TeQTabanca** [comment]
### and this error pops up when the server starts up

```
[18:22:19 ERROR]: [DailyShop] An error occurred executing an SQLite query: [?]Unable to parse Malformed Json!
[18:22:19 WARN]: io.github.divios.dependencies.nbt.nbtapi.NbtApiException: [?]Unable to parse Malformed Json!
[18:22:19 WARN]:        at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:68)
[18:22:19 WARN]:        at io.github.divios.lib.dLib.dItem.fromJson(dItem.java:712)
[18:22:19 WARN]:        at io.github.divios.lib.dLib.dItem.fromBase64(dItem.java:708)
[18:22:19 WARN]:        at io.github.divios.lib.storage.dataManager.lambda$getShop$3(dataManager.java:82)
[18:22:19 WARN]:        at io.github.divios.dependencies.Core_lib.database.SQLiteConnector.connect(SQLiteConnector.java:56)
[18:22:19 WARN]:        at io.github.divios.lib.storage.dataManager.lambda$getShop$4(dataManager.java:76)
[18:22:19 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[18:22:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[18:22:19 WARN]: Caused by: java.lang.NullPointerException
[18:22:19 WARN]:        at io.github.divios.dependencies.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180)
[18:22:19 WARN]:        at io.github.divios.dependencies.nbt.nbtapi.NBTContainer.<init>(NBTContainer.java:66)
[18:22:19 WARN]:        ... 7 more
[18:22:19 WARN]: [NBTAPI] The NBT-API located at 'package io.github.divios.dependencies.nbt.nbtapi' seems to be outdated!
[18:22:19 WARN]: [NBTAPI] Current Version: '2.9.2-SNAPSHOT' Newest Version: 2.9.2'
[18:22:19 WARN]: [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!
```

**Comment by divios** [comment]
Hi! I thought you had the premium version. The free and premium version are not backwards compatible, so you have to delete the .db file ( you will lose tour shops)

**Comment by TeQTabanca** [comment]
**I already deleted the Dailyshop folder, but every time it is opened, this error appears.**

**Comment by TeQTabanca** [comment]
**There is a premium version, but if I set minprice:maxprice to an item, that item gets copied to many places, so I don't want to use the premium version.**

![minPrice-maxPrice](https://user-images.githubusercontent.com/89253304/158074348-b737fe59-8455-456a-8916-27e9b9a59c27.png)
